export const FIELD = {
  USER_EMAIL_MAX_LENGTH: 50,
  USER_PASSWORD_MAX_LENGTH: 25,
  USER_FIRST_NAME_MAX_LENGTH: 50,
  USER_LAST_NAME_MAX_LENGTH: 50,

  EXPEDIENT_CODE_MAX_LENGTH: 100,
  EXPEDIENT_SUBJECT_MAX_LENGTH: 100,
  EXPEDIENT_COURT_MAX_LENGTH: 100,

  PART_NAME_MAX_LENGTH: 50,

  DOCUMENT_NAME_MAX_LENGTH: 200,
  DOCUMENT_URL_MAX_LENGTH: 200,
  DOCUMENT_TYPE_MAX_LENGTH: 5,
}

export enum EXPEDIENT_STATUS {
  TACHADO = 'TACHADO',
  EJECUCION = 'EJECUCION'
}

export enum PART_TYPES {
  DENUNCIANTE = 'DENUNCIANTE',
  DENUNCIADO = 'DENUNCIADO'
}

export enum USER_ROLES {
  ADMIN = 'ADMIN',
  ABOGADO = 'ABOGADO',
  PRACTICANTE = 'PRACTICANTE'
}

